// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYoOmgXstP1_gByDY78CYb4SFzkBQdcqs',
    appId: '1:396414324120:web:96e8283723776c9f466fed',
    messagingSenderId: '396414324120',
    projectId: 'sy-21days-fb-auth',
    authDomain: 'sy-21days-fb-auth.firebaseapp.com',
    storageBucket: 'sy-21days-fb-auth.firebasestorage.app',
    measurementId: 'G-GHBE2RR0LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG4nMYZdJbNQoEquhYNTsdenp4z5lCrCU',
    appId: '1:396414324120:android:0345b9e943c54a6d466fed',
    messagingSenderId: '396414324120',
    projectId: 'sy-21days-fb-auth',
    storageBucket: 'sy-21days-fb-auth.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpUAaShV8zYvcz-BNaThYKrRm8bGEQ1f0',
    appId: '1:396414324120:ios:519f7c905ca355fc466fed',
    messagingSenderId: '396414324120',
    projectId: 'sy-21days-fb-auth',
    storageBucket: 'sy-21days-fb-auth.firebasestorage.app',
    iosClientId: '396414324120-1bqui91ipuh7okqi4090d43men3kjdn2.apps.googleusercontent.com',
    iosBundleId: 'com.sahajayoga.twentyOneDays',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpUAaShV8zYvcz-BNaThYKrRm8bGEQ1f0',
    appId: '1:396414324120:ios:519f7c905ca355fc466fed',
    messagingSenderId: '396414324120',
    projectId: 'sy-21days-fb-auth',
    storageBucket: 'sy-21days-fb-auth.firebasestorage.app',
    iosClientId: '396414324120-1bqui91ipuh7okqi4090d43men3kjdn2.apps.googleusercontent.com',
    iosBundleId: 'com.sahajayoga.twentyOneDays',
  );
}
